### ISSUE TITLE
홈 화면 정보 게시판 제목 연결

### ISSUE THREAD

**Issue by Bamgarim** [KNUT-Hackathon/Networker#63]
정보 게시판 간격 수정, 홈 화면 정보 게시판 제목 불러오는 기능 추가했습니다 추가로 개인정보처리방침 링크 연결도 완료했습니다

**Comment by MystyS2** [comment]
- 홈 화면에서 정보글을 불러올 때 로컬 스토리지를 활용한 방식으로 구현되어 있어, 처음 웹페이지에 접속하는 사용자는 해당 정보가 뜨지 않는 문제가 있음
